Repository ProyectoEgc/decide-single-picasso, pull requests merged in 2023-12, with the labels that each got.

#49 bug(initial): Closed Votings bug
  decide/authentication/templates/authentication/decide.html
Labels: bug

#52 add(initial): French translation
  decide/authentication/templates/signup.html
  decide/decide/settings.py
  decide/locale/fr/LC_MESSAGES/django.po
Labels: feature, task

#55 Feature5/jaicabher1
  decide/authentication/tests.py
  decide/authentication/urls.py
Labels: bug, testing

#60 Feature16/alvsanflo jaicabher1
  .gitmessage.txt
  decide/booth/templates/booth/booth.html
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
  decide/voting/models.py
  decide/voting/tests.py
  decide/voting/views.py
  proyectoenv/bin/Activate.ps1
  proyectoenv/bin/activate
  proyectoenv/bin/activate.csh
  proyectoenv/bin/activate.fish
  proyectoenv/bin/coverage
  proyectoenv/bin/coverage-3.10
  proyectoenv/bin/coverage3
  proyectoenv/bin/django-admin
  proyectoenv/bin/flask
  proyectoenv/bin/locust
  proyectoenv/bin/normalizer
  proyectoenv/bin/nosetests
  proyectoenv/bin/nosetests-3.4
  proyectoenv/bin/pip
  proyectoenv/bin/pip3
  proyectoenv/bin/pip3.10
  proyectoenv/bin/pynose
  proyectoenv/bin/python
  proyectoenv/bin/python3
  proyectoenv/bin/python3.10
  proyectoenv/bin/sqlformat
  proyectoenv/include/site/python3.10/greenlet/greenlet.h
  proyectoenv/lib64
  proyectoenv/man/man1/nosetests.1
  proyectoenv/pyvenv.cfg
Labels: feature, task, testing

#62 add(update): Image Voting
  decide/booth/templates/booth/booth.html
  decide/decide/settings.py
  decide/decide/urls.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/views.py
Labels: feature

#69 fix(initial): Fix requirements.txt
  requirements.txt
Labels: bug, task

#76 test(initial): Authentication test
  decide/authentication/test_selenium_create_user.py
  decide/authentication/test_selenium_negative_create_user.py
Labels: testing

#77 test(update): Add multiple voting
  decide/census/migrations/0001_initial.py
  decide/census/migrations/__init__.py
  decide/decide/settings.py
  decide/voting/test_selenium_negative_create_multiple_voting.py
  decide/voting/test_selenium_negative_create_question.py
  decide/voting/tests.py
Labels: testing

#79 add(initial): Score voting selenium
  decide/base/tests.py
  decide/voting/test_selenium_create_score_question.py
  decide/voting/test_selenium_create_score_question_negative.py
Labels: testing

#80 add(update): Yes No Tests
  decide/voting/test_selenium_create_yes_no_question.py
  decide/voting/tests.py
Labels: testing

#81 add(end): Score voting tests
  decide/postproc/tests.py
  decide/voting/tests.py
Labels: testing

#83 fix(update): Test failing in develop branch
  .github/workflows/django.yml
  decide/send_email.py
  decide/voting/test_selenium_negative_create_multiple_voting.py
  decide/voting/tests.py
Labels: bug, testing, deploy

#84 test(update): Import and export census data
  decide/census/static/EmptyFile.xls
  decide/census/static/WrongType.ods
  decide/census/static/censoTestImport.xlsx
  decide/census/test_selenium_export.py
  decide/census/test_selenium_import.py
Labels: testing

#85 test(update): Image Voting
  decide/voting/static/1.jpeg
  decide/voting/static/2.jpeg
  decide/voting/test_selenium.py
  decide/voting/tests.py
Labels: testing

#86 fix(update): Tests failling in develop branch
  decide/census/test_selenium_export.py
  decide/census/test_selenium_import.py
  decide/voting/test_selenium_negative_create_multiple_voting.py
Labels: bug, testing

#88 fix(update): Fix Actions
  .github/workflows/django.yml
  decide/authentication/test_selenium_create_user.py
  decide/authentication/test_selenium_negative_create_user.py
  decide/authentication/tests_selenium.py
  decide/send_email.py
  decide/voting/test_selenium_negative_create_multiple_voting.py
  decide/voting/test_selenium_negative_create_question.py
Labels: bug, testing

#89 test(update): User register
  decide/authentication/tests_selenium.py
Labels: testing

#90 fix(update): Fix actions
  .github/workflows/django.yml
Labels: bug, testing

#91 fix(update): Fix actions
  .github/workflows/django.yml
Labels: bug, testing, deploy

#92 fix(update): Fix actions
  .github/workflows/django.yml
Labels: bug, testing, deploy

#94 add(initial): deployment configuration
  decide/census/migrations/0001_initial.py
  decide/local_settings.deploy.py
  launch.sh
  requirements.txt
Labels: deploy

#96 fix(update): Failing tests in develop branch
  .github/workflows/django.yml
  decide/authentication/test_selenium_create_user.py
  decide/census/test_selenium_export.py
  decide/census/test_selenium_import.py
  decide/voting/test_selenium.py
  decide/voting/test_selenium_create_score_question.py
  decide/voting/test_selenium_create_score_question_negative.py
  decide/voting/test_selenium_create_yes_no_question.py
  decide/voting/test_selenium_positive_create_multiple_voting.py
  requirements.txt
Labels: bug

#97 test(update): Image Voting
  decide/voting/test_selenium.py
  decide/voting/tests.py
Labels: bug, testing

#98 fix(update): Failing tests in develop branch
  decide/authentication/test_selenium_create_user.py
  decide/authentication/test_selenium_negative_create_user.py
  decide/authentication/tests_selenium.py
  decide/media/images/1.jpeg
  decide/media/images/1_3Rk5nuz.jpeg
  decide/media/images/1_4WgTion.jpeg
  decide/media/images/1_CESBpLE.jpeg
  decide/media/images/1_IqFm1ZA.jpeg
  decide/media/images/1_TdenW6x.jpeg
  decide/media/images/1_XDBiP6m.jpeg
  decide/media/images/1_iEZ8IkC.jpeg
  decide/media/images/1_jhP6GqO.jpeg
  decide/media/images/2.jpeg
  decide/media/images/2_36Mq7zF.jpeg
  decide/media/images/2_75DYYkQ.jpeg
  decide/media/images/2_GJ2PKJ4.jpeg
  decide/media/images/2_Lfg4ZGd.jpeg
  decide/media/images/2_cnjzlgq.jpeg
  decide/media/images/2_fSDFBEP.jpeg
  decide/media/images/2_qH5L5BO.jpeg
  decide/media/images/2_t63Xge2.jpeg
  decide/voting/test_selenium.py
  decide/voting/test_selenium_negative_create_multiple_voting.py
Labels: bug, testing

#100 add(initial): Tests CI bug
  decide/authentication/test_selenium_create_user.py
  decide/authentication/test_selenium_negative_create_user.py
  decide/authentication/tests_selenium.py
  decide/census/test_selenium_export.py
  decide/census/test_selenium_import.py
  decide/voting/test_selenium.py
  decide/voting/test_selenium_create_score_question.py
  decide/voting/test_selenium_create_score_question_negative.py
  decide/voting/test_selenium_create_yes_no_question.py
  decide/voting/test_selenium_negative_create_multiple_voting.py
  decide/voting/test_selenium_negative_create_question.py
  decide/voting/test_selenium_positive_create_multiple_voting.py
Labels: bug, testing

#105 Render deployment
  .github/ISSUE_TEMPLATE/bug_report.md
  .gitmessage.txt
  decide/authentication/test_selenium_create_user.py
  decide/authentication/test_selenium_negative_create_user.py
  decide/authentication/tests_selenium.py
  decide/census/test_selenium_export.py
  decide/census/test_selenium_import.py
  decide/voting/test_selenium.py
  decide/voting/test_selenium_create_score_question.py
  decide/voting/test_selenium_create_score_question_negative.py
  decide/voting/test_selenium_create_yes_no_question.py
  decide/voting/test_selenium_negative_create_multiple_voting.py
  decide/voting/test_selenium_negative_create_question.py
  decide/voting/test_selenium_positive_create_multiple_voting.py
Labels: deploy

#107 Task26/alvsanflo1
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
Labels: deploy

#108 Develop
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
Labels: deploy

#110 feautre(initial): IMport new census
  decide/decide/settings.py
Labels: feature
