Repository ProyectoEgc/decide-single-picasso, pull requests merged in 2023-11, with the labels that each got.

#29 refactor(update):Fixed error
  .github/workflows/django.yml
Labels: bug

#30 refactor(fix):Fixed django.yml
  .github/workflows/django.yml
Labels: task

#31 refactor(update):Fixed
  .github/workflows/django.yml
Labels: task

#33 Docs(init): Done bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#35 fix(init):voting and store tests
  decide/voting/migrations/0005_question_type.py
  decide/voting/tests.py
Labels: bug

#36 delete(init):Test Selenium
  decide/authentication/test_selenium.py
  decide/visualizer/test_selenium.py
Labels: bug

#40 Feature6/jaicabher1
  decide/authentication/templates/authentication/decide.html
  decide/authentication/templates/authentication/login.html
  decide/authentication/templates/signup.html
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/booth/templates/booth/booth.html
  decide/decide/settings.py
  decide/locale/es/LC_MESSAGES/django.po
  decide/visualizer/templates/visualizer/visualizer.html
Labels: feature, task
